# Generated by Django 3.2.2 on 2021-05-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0006_application_categoryevent_event_faq_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentor', verbose_name='mentor')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.course')),
            ],
            options={
                'verbose_name': 'Ментора',
                'verbose_name_plural': 'Менторы',
            },
        ),
    ]
