# Generated by Django 3.2.2 on 2021-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0007_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='whatsapp_number',
            new_name='phone_number2',
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
