# Generated by Django 3.2.2 on 2021-07-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0010_remove_mentor_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
