# Generated by Django 3.2.2 on 2021-07-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0012_rename_name_course_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nam',
            new_name='name',
        ),
    ]
