# Generated by Django 3.2.2 on 2021-07-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0013_rename_nam_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mail',
        ),
        migrations.DeleteModel(
            name='CategoryEvent',
        ),
    ]
