# Generated by Django 3.2.2 on 2021-07-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0014_auto_20210729_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantages',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
