# Generated by Django 3.2.2 on 2021-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0015_auto_20210729_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
