# Generated by Django 3.2.2 on 2021-07-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0016_course_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'FAQCourse',
                'verbose_name_plural': 'FAQCourse',
            },
        ),
    ]
