# Generated by Django 3.2.2 on 2021-07-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0017_faqcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.course'),
        ),
    ]
