# Generated by Django 3.2.2 on 2021-07-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0018_mentor_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.mentor'),
        ),
    ]
