# Generated by Django 3.2.2 on 2021-07-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0019_auto_20210729_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='ImageCourseDetail', verbose_name='Изображение')),
            ],
        ),
    ]
