# Generated by Django 3.2.2 on 2021-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0021_auto_20210729_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCourseDetail',
        ),
        migrations.AddField(
            model_name='course',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='course',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение'),
        ),
    ]
